#!/bin/fish
echo
echo $USER@$(hostname)
date
echo ---------------------------------------------
echo Welcome To
figlet "$(cat /etc/os-release | grep -w NAME | head -1 | sed 's/NAME==//g' | sed 's/\"//g' | sed s:NAME=::)" | lolcat
export memtot="$(grep MemTotal /proc/meminfo | sed 's/MemTotal/Total Memory/g')"
export memfree="$(grep MemFree /proc/meminfo | sed 's/MemFree/Free Memory/g')"
echo "  $memtot, $memfree"
echo "  $XDG_CURRENT_DESKTOP"
echo "  $(uptime -p)"
export gpu="$(inxi -G | grep Device-2: | sed 's/Device-2://g' | awk -F 'driver' '{print $1"driver"}' | sed 's/\\[/name: /' | sed 's/^.*: //' | cut -f1 -d"]")"
echo "󰻑 $gpu"
